services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHROME_EXTENSION_API_BASE_URL: "https://open-manga.agevon.com"
    container_name: manga-nextjs
    ports:
      - "3080:3080"
    environment:
      NODE_ENV: "production"
      ALLOW_REMOTE_SETUP: "1"
      SECTION_IMAGE_PROCESSING_CONCURRENCY: "2"
      CHROME_EXTENSION_API_BASE_URL: "https://open-manga.agevon.com"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
