// Generated by scripts/generate-extension-config.mjs.
// Do not edit manually; set CHROME_EXTENSION_API_BASE_URL, NEXT_PUBLIC_SITE_URL,
// SITE_URL, APP_URL, PUBLIC_URL, or NEXT_PORT before npm run dev/build/start.
self.MTL_EXTENSION_CONFIG = Object.freeze({
  apiBaseUrl: "http://localhost:3080",
  sourceLang: "auto",
  targetLang: "pt-BR",
  providerLang: "google",
});
